version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /preprocessing-for-group-assignment-co-assembly.ga
  testParameterFiles:
  - /preprocessing-for-group-assignment-co-assembly-tests.yml
  authors:
  - name: ''
    identifier: ''
    isNew: true
  - name: ''
    identifier: ''
    isNew: true
  - name: Mina Hojat Ansari
    orcid: 0000-0002-3602-7884
  - name: Paul Zierep
    orcid: 0000-0003-2982-388X
